---
#    __  __ _                ____        _   _   _
#   |  \/  (_) ___ _ __ ___ | __ )  __ _| |_| |_| | ___  ___
#   | |\/| | |/ __| '__/ _ \|  _ \ / _` | __| __| |/ _ \/ __|
#   | |  | | | (__| | | (_) | |_) | (_| | |_| |_| |  __/\__ \
#   |_|  |_|_|\___|_|  \___/|____/ \__,_|\__|\__|_|\___||___/

# Modify Economy here
economy:
  enabled: true
  # List of Support Plugins:
  # - EconomyAPI
  provider: EconomyAPI
...